### ISSUE TITLE
Crash when joining the world ins specific blocks

### ISSUE THREAD

**Issue by iacuobos** [Leawind/Third-Person#115]
version 1.20.1
seems to be something related to a position i left the game in.

## When
* Joining a world
* Enter third person
* Some situation

## Crash report

java.lang.ClassCastException: class net.minecraft.class_4618 cannot be cast to class net.minecraft.class_4597$class_4598 (net.minecraft.class_4618 and net.minecraft.class_4597$class_4598 are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @72035809)
	at net.minecraft.class_761.handler$cdk000$leawind_third_person$renderEntity_tail(class_761.java:30943)
	at net.minecraft.class_761.method_22977(class_761.java:1575)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

Seems to be something related to tailing a entity... not sure?

**Comment by Leawind** [comment]
Maybe it has been fixed in the latest 2.0.8-1.20.1
Could you update and try again see see?

**Comment by iacuobos** [comment]
Seems to be fixed

**Comment by Leawind** [comment]
It's fixed in ff3dac80d90e8210705d26e1e27f96e2f23afa38
