### ISSUE TITLE
Game crash on scroll - version 1.20.2

### ISSUE THREAD

**Issue by Zirimiri** [Leawind/Third-Person#61]
The mod works fine until I try to scroll to a different HUD slot, and it crashes immediately. In the code I noticed this: 
`Unreported exception thrown!
java.lang.AbstractMethodError: Receiver class net.leawind.mc.thirdperson.ThirdPersonEvents$$Lambda$6636/0x000002bb82104018 does not define or inherit an implementation of the resolved method 'abstract dev.architectury.event.EventResult mouseScrolled(net.minecraft.class_310, double, double)' of interface dev.architectury.event.events.client.ClientRawInputEvent$MouseScrolled.
at net.minecraft.class_312.handler$zdi000$architectury$onRawMouseScrolled(class_312.java:1076) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_1598(class_312.java:157) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_22687(class_312.java:181) ~[client-intermediary.jar:?]
at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_22685(class_312.java:181) ~[client-intermediary.jar:?]
at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:44) ~[lwjgl-glfw-3.3.2.jar:?]
at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1523(class_310.java:1300) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.15.6.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]`

Here's the whole log: https://mclo.gs/3nUkQFy

**Comment by Zirimiri** [comment]
mod version 2.0.8-beta.3

**Comment by Leawind** [comment]
I see you are using 1.20.2, which is not expected to be supported by now.
The latest published version is for 1.20.1

**Comment by ArctynFox** [comment]
This is the same issue as https://github.com/LEAWIND/Third-Person/issues/86. Try using the jar files I compiled for https://github.com/LEAWIND/Third-Person/pull/88 which I link my response there and see if it fixes the issue. The jar files are intended for 1.20.4, but the crash present there was due to the same error, and should be resolved.
