### ISSUE TITLE
Crash when a glowing effect is applied to the flying player

### ISSUE THREAD

**Issue by PierreHervelin** [Leawind/Third-Person#93]
## When

Select one:

* launch client
* Join a world
* Enter third person
* Use commands in that order : 
```
/gamemode creative
```
```
/effect @a minecraft:glowing
```
* Then start flying

I also had the bug in survival with elytra

## Crash report

```
[12:51:46] [Render thread/INFO]:
 [System] [CHAT] Applied effect Glowing to {MINECRAFT_USERNAME}
[12:51:58] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.ClassCastException: class net.minecraft.class_4618 cannot be cast to class net.minecraft.class_4597$class_4598 (net.minecraft.class_4618 and net.minecraft.class_4597$class_4598 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @598067a5)
	at net.minecraft.class_761.handler$dmf000$leawind_third_person$renderEntity_tail(class_761.java:20503) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1575) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1324) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[12:51:58] [Render thread/INFO]:
 Minimap session finalized.
[12:51:58] [Render thread/INFO]:
 Finalizing world map session...
[12:51:58] [Thread-28/INFO]:
 World map force-cleaned!
[12:51:58] [Render thread/INFO]:
 World map session finalized.
[12:51:58] [Render thread/INFO]:
 Stopping worker threads
```

**Comment by PierreHervelin** [comment]
duplicate of #80 (my bad)
